let products = [
    {
        "id": 1001,
        "title": "Math",
        "description": "Math is a crucial subject to learning success, which students will continue through each grade of their school journey.",
        "price": 970,
        "location": "Malta",
        "image": "images/product-math.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1002,
        "title": "English",
        "description": "English is spoken in every country, and by this it is not our native language but we have the best set of teachers to put you through.",
        "price": 570,
        "location": "Kano",
        "image": "images/product-english.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1003,
        "title": "Volleyball",
        "description": "Volleyball is a team soprt which two twams of six payers are seperated by a net.",
        "price": 300,
        "location": "Abuja",
        "image": "images/product-volleyball.jpg",
        "availableInventory": 5, 
        "rating": 2,
    },
    {
        "id": 1004,
        "title": "Rugby",
        "description":  "Rugby is a football game oval ball by two teams.",
        "price": 230,
        "location": "USA",
        "image": "images/product-rugby.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1005,
        "title": "Music",
        "description":"Music brings a different vibe to the body and soul,come enjoy and explore the world of music and various instruments.",
        "price": 160,
        "location": "Abuja",
        "image": "images/product-music.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1006,
        "title": "Judo",
        "description": "The art of judo is a very lovely skill to harness.",
        "price": 170,
        "location": "Malta",
        "image": "images/product-judo.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1007,
        "title": "Redcross",
        "description": "Red cross is also as a first squard for emegency happenings.",
        "price": 900,
        "location": "London",
        "image": "images/product-red cross.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1008,
        "title": "Reading",
        "description": "Reading is the process of looking at some written symbols and getting the meaning of them.",
        "price": 190,
        "location": "London",
        "image": "images/product-reading.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1009,
        "title": "Swimming",
        "description": "Swimming helps build your cardio, helps ease stress and relax, we have top trainers ready to help put your child through.",
        "price": 295,
        "location": "Abuja",
        "image": "images/product-swim.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1010,
        "title": "Science",
        "description": "Science is a combination of two or more element.",
        "price": 188,
        "location": "Kano",
        "image": "images/product-science.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
]